[tool.poetry]
name = "neosr"
version = "0.1.0"
description = "neosr, a framework for training real-world single-image super-resolution networks."
authors = ["musl"]
license = "Apache 2.0"
readme = "readme.md"

[tool.poetry.dependencies]
python = "^3.11,<3.12"
numpy = "^1.25.2"
lmdb = "^1.4.1"
einops = "^0.6.1"
pytorch-optimizer = "^2.11.1"
scipy = "^1.11.1"
PyYAML = "^6.0.1"
tb-nightly = "^2.14.0a20230802"
tqdm = "^4.65.0"
opencv-python-headless = "^4.8.1.78"
packaging = "^23.2"
torch = "^2.1"
torchvision = "^0.16"

[tool.ruff]
select = ["ALL"]
ignore = ["E501"]
target-version = "py311"
preview = true

[tool.ruff.format]
skip-magic-trailing-comma = true
line-ending = "lf"

[tool.ruff.lint.mccabe]
max-complexity = 5

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
